CREATE DATABASE $(ANIMAL_DATABASE);

CREATE USER $(ANIMAL_USER) WITH PASSWORD '$(ANIMAL_PASSWORD)';

GRANT ALL PRIVILEGES ON DATABASE $(ANIMAL_DATABASE) TO $(ANIMAL_USER);

\c $(ANIMAL_DATABASE);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $(ANIMAL_USER);